version: "3.9"

services:
  chrome:
    container_name: task_presenter_chrome
    image: selenium/standalone-chrome:130.0-chromedriver-130.0
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm

  mysql:
    container_name: task_presenter_mysql
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: task_presenter
      # MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ../../docker/development/mysql/provision/init:/docker-entrypoint-initdb.d
      - ../../docker/development/mysql/volume:/var/lib/mysql

  rails:
    build:
      context: ../..
      dockerfile: ./docker/development/rails/Dockerfile
    container_name: task_presenter_rails
    depends_on:
      - mysql
      - redis
    environment:
      ACTION_CABLE_CHANNEL_PREFIX: task_presenter_action_cable
      CHROME_CONTAINER_HOST: chrome
      CHROME_CONTAINER_PORT: 4444
      MYSQL_CONTAINER_HOST: mysql
      MYSQL_CONTAINER_PORT: 3306
      MYSQL_DATABASE_PREFIX: task_presenter
      MYSQL_PASSWORD: password
      MYSQL_USER: root
      REDIS_URL: redis://redis:6380
      TURNIP_RAILS_CONTAINER_PORT: 4000
    stdin_open: true
    tty: true
    volumes:
      - ../..:/rails

  redis:
    container_name: task_presenter_redis
    image: redis:7.4
    volumes:
      - ../../docker/development/redis/volume:/var/lib/redis/data
    command: redis-server --port 6380
