const DISPLAY_MODES = {
  VERTICAL_LIST: 'VERTICAL_LIST',
  HORIZONTAL_GRID: 'HORIZONTAL_GRID'
}

const NEXT_DISPLAY_MODES = {
  VERTICAL_LIST: 'HORIZONTAL_GRID',
  HORIZONTAL_GRID: 'VERTICAL_LIST'
}

export {
  DISPLAY_MODES,
  NEXT_DISPLAY_MODES
}
